# Generated by Django 4.2 on 2023-05-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
